//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coment_section
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public string user_name { get; set; }
        public string coment { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string edit_value { get; set; }
    }
}
