//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_id { get; set; }
        public string Customer_res_name { get; set; }
        public string Customer_user { get; set; }
        public string Customer_pw { get; set; }
        public string Customer_name { get; set; }
        public string Customer_last_name { get; set; }
        public string Address_C_id_fk { get; set; }
        public string Customer_email { get; set; }
        public string Customer_phone { get; set; }
        public string Customer_pic { get; set; }
        public string Customer_open { get; set; }
        public string Customer_close { get; set; }
        public int Location_C_id { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
    }
}
