//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int id { get; set; }
        public string description1 { get; set; }
        public string customer_name { get; set; }
        public string edit_value { get; set; }
    }
}
