//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Picture
    {
        public int Food_Picture_id { get; set; }
        public string C_FK_Customer_id { get; set; }
        public string Food_Picture_pic { get; set; }
        public string Food_Picture_name { get; set; }
    }
}
