//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Get_location
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public string address_street { get; set; }
        public string address_district { get; set; }
        public string address_county { get; set; }
        public string address_zip { get; set; }
        public string status { get; set; }
        public string address_province { get; set; }
    }
}
