//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_C
    {
        public int Location_C_id { get; set; }
        public string Location_C_number { get; set; }
        public string Address_C_street { get; set; }
        public string Address_C_province { get; set; }
        public string Address_C_district { get; set; }
        public string Address_C_sub_dstrict { get; set; }
        public string Address_C_postal_code { get; set; }
        public string Address_C_location_type { get; set; }
    }
}
