//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Order_Food_dbEntities : DbContext
    {
        public Order_Food_dbEntities()
            : base("name=Order_Food_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user_account> user_account { get; set; }
        public virtual DbSet<Address_C> Address_C { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Food_Picture> Food_Picture { get; set; }
        public virtual DbSet<Location_C> Location_C { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
