//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_id { get; set; }
        public int C_FK_Order_id { get; set; }
        public int C_FK_Menu_id { get; set; }
    }
}
