//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Get_storename = new HashSet<Get_storename>();
        }

        public int User_id { get; set; }
        [Required(ErrorMessage = "*")]
        public string User_user { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "*")]
        public string User_pw { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "*")]
        public string User_repw { get; set; }
        [Required(ErrorMessage = "*")]
        public string User_name { get; set; }
        [Required(ErrorMessage = "*")]
        public string User_last_name { get; set; }
        public Nullable<int> C_FK_Address_U { get; set; }
        public Nullable<int> C_FK_Location_U_id { get; set; }
        [Required(ErrorMessage = "*")]
        public string User_phone { get; set; }
        [Required(ErrorMessage = "*")]
        public string Status { get; set; }
        public string Province { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Get_storename> Get_storename { get; set; }
    }
}
