//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_showing
    {
        public string User_user { get; set; }
        public string day_open { get; set; }
        public string day_close { get; set; }
        public string time_close { get; set; }
        public string description { get; set; }
        public string add_img { get; set; }
        public string get_storename { get; set; }
        public string time_open { get; set; }
    }
}
